//------------------------------------------------------------------------
// Copyright(c) 2024 redetach.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"MultiDist.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"MultiDist VST3 (64Bit)"
#else
#define stringFileDescription	"MultiDist VST3"
#endif
#define stringCompanyName		"redetach\0"
#define stringLegalCopyright	"Copyright(c) 2024 redetach."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
